<?xml version="1.0" encoding="UTF-8"?>

<!--
  * crosswalks.xml
  *
  * Copyright (c) 2005-2006 The Public Knowledge Project
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Default crosswalks.
  *
  * $Id$
  -->

<!DOCTYPE crosswalks [
	<!ELEMENT crosswalks (crosswalk+)>
	<!ELEMENT crosswalk (name, description, field+)>
	<!ATTLIST crosswalk
		type (text | string) #IMPLIED
		sortable (true | false) #IMPLIED>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT field EMPTY>
	<!ATTLIST field 
		schema CDATA #REQUIRED
		name CDATA #REQUIRED>
]>

<crosswalks>
	<crosswalk type="text" sortable="true">
		<name>Title</name>
		<description>This crosswalk associates the title fields from various schemas.</description>
		<field schema="DublinCorePlugin" name="title"/>
		<field schema="MarcPlugin" name="130"/>
		<field schema="MarcPlugin" name="210"/>
		<field schema="MarcPlugin" name="222"/>
		<field schema="MarcPlugin" name="240"/>
		<field schema="MarcPlugin" name="242"/>
		<field schema="MarcPlugin" name="243"/>
		<field schema="MarcPlugin" name="245"/>
		<field schema="MarcPlugin" name="246"/>
		<field schema="MarcPlugin" name="247"/>
		<field schema="ModsPlugin" name="title"/>
		<field schema="ModsPlugin" name="subTitle"/>
		<field schema="ModsPlugin" name="partName"/>
		<field schema="ModsPlugin" name="nonSort"/>
		<field schema="ModsPlugin" name="displayForm"/>
	</crosswalk>
	<crosswalk type="text" sortable="false">
		<name>Author</name>
		<description>This crosswalk associates the creator / author fields from various schemas.</description>
		<field schema="DublinCorePlugin" name="creator"/>
		<field schema="MarcPlugin" name="720"/>
		<field schema="ModsPlugin" name="namePart"/>
	</crosswalk>
	<crosswalk type="date" sortable="true">
		<name>Date</name>
		<description>This crosswalk associates a generic date, generally creation, from the various schemas.</description>
		<field schema="DublinCorePlugin" name="date"/>
		<field schema="MarcPlugin" name="260"/>
		<field schema="ModsPlugin" name="dateCreated"/>
	</crosswalk>
</crosswalks>
