<?xml version="1.0" encoding="UTF-8"?>
<!--
  * version.xml
  *
  * Copyright (c) 2005-2008 Alec Smecher and John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Harvester2 version information.
  *
  * $Id$
  -->

<!DOCTYPE version [
	<!ELEMENT version (application, type, release, tag, date, info, package, patch*)>
	<!ELEMENT application (#PCDATA)>
	<!ELEMENT type (#PCDATA)>
	<!ELEMENT release (#PCDATA)>
	<!ELEMENT tag (#PCDATA)>
	<!ELEMENT date (#PCDATA)>
	<!ELEMENT info (#PCDATA)>
	<!ELEMENT package (#PCDATA)>
	<!ELEMENT patch (#PCDATA)>
		<!ATTLIST patch
			from CDATA #REQUIRED>
]>

<version>
	<application>harvester2</application>
	<type>core</type>
	<release>2.3.0.0</release>
	<tag>harvester-2_3_0-0</tag>
	<date>2009-02-18</date>
	<info>http://pkp.sfu.ca/harvester2/</info>
	<package>http://pkp.sfu.ca/harvester2/download/harvester-2.3.0.tar.gz</package>
	<patch from="2.0.0.0">http://pkp.sfu.ca/harvester2/download/patch/harvester-2.0_to_2.3.patch.gz</patch>
	<patch from="2.0.1.0">http://pkp.sfu.ca/harvester2/download/patch/harvester-2.0.1_to_2.3.patch.gz</patch>
</version>
